name: Selenium Test Automation Framework

on:
  schedule: 
  - cron: 40 07 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run with Maven
      run: mvn test -X -Denv=qa -Dbrowser="chrome,firefox"

    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
        name: Test logs
        path: logs/
    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
        name: allure-report
        path: target/allure-results
        
    - name: Test Execution status
      run: echo "Test Execution complete!"
      
